baseURL = "/"
languageCode = "de-de"
title = "Torganisiertes Spiel"
theme = "personal-web"
copyright="© Torganisiertes Spiel"
googleAnalytics = ""
enableEmoji=true
enableRobotsTXT=true
pygmentsUseClasses=true
pygmentsCodeFences=true

[params.intro]
  main = "Torganisiertes Spiel"
  sub = "Wir organisieren Torg-Spiele im deutschsprachigen Raum"

[params.main]
  latestPublishHeader = "Letzte Meldung"

[taxonomies]
  realm = "Realität"
  clearance = "Freigabe"

[blackfriday]
  hrefTargetBlank = true

[params]
  breadcrumb = true
  accentColor = "#FD3519"
  mainSections = ['post']

[params.notFound]
  gopher = "/images/delphi-council.png"
  h1 = 'Bummer!'
  p = "Diese Seite existiert nicht in dieser Realität."

[params.sections]
  # Define how your sections will be called
  # when automatically pulled. For instance in the 404 page
  post = "article"
  portfolio = "rules"

[params.sidebar]
  backgroundImage = '/images/bg.png'
  gradientOverlay = '' # default: rgba(0,0,0,0.4),rgba(0,0,0,0.4)
  logo = "/images/delphi-council.png"
[params.assets]
  favicon = ""
  customCSS = ""

[params.social]
#  github = "https://github.com/"
#  twitter = "https://twitter.com/"
#  linkedin = "https://www.linkedin.com/in/"
#  medium = "https://medium.com/"
#  codepen = "https://codepen.io/"
#  facebook = "https://www.facebook.com/"
#  youtube = "https://www.youtube.com/"
#  instagram = "https://www.instagram.com/"
#  gitlab = "https://gitlab.com/"
#  keybase = "https://keybase.io/"

[params.contact]
  email = "info@de.torganized-play.de"
  text= "" # text of the contact link in the sidebar. If email params.contact.email is defined


[menu]

[[menu.main]]
  identifier = "blog"
  name = "Neuigkeiten"
  title = "Neuigkeiten vom Delphi-Rat"
  url = "/post/"
  weight = -200

[[menu.main]]
  identifier = "realities"
  name = "Realitäten"
  title = "Realitäten"
  url = "/realities/"
  weight = -190

[[menu.main]]
  identifier = "missions"
  name = "Szenarien"
  title = "Szenarien"
  url = "/missions/"
  weight = -180

[[menu.main]]
  identifier = "rules"
  name = "Regeln"
  title = "Regeln"
  url = "/rules/"
  weight = -170



[[menu.main]]
  identifier = "about"
  name = "Über uns"
  title = "Über das Torganisierte Spiel"
  url = "/about/"
  weight = -20

[[menu.main]]
  identifier = "faq"
  name = "F.A.Q."
  title = "F.A.Q."
  url = "/faq/"
  weight = -10

[[menu.main]]
  identifier = "impressum"
  name = "Impressum"
  title = "Impressum"
  url = "/impressum/"
  weight = 0

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.twitter]
    disable = true
    enableDNT = true
    simple = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
