{{ $fullname := include "hugo-static.fullname" . }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $fullname }}-trigger-secret
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  labels:
    {{- include "hugo-static.labels" . | nindent 4 }}
spec:
  encryptedData:
    WebHookSecretKey: {{ .Values.source.triggerSecret }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        {{- include "hugo-static.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/managed-by: SealedSecrets
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
      name: {{ $fullname }}-trigger-secret

